#!/usr/bin/env python3
"""
train_saa_model.py

Train machine learning model to predict sulfur-containing amino acid (SAA) frequency

Prerequisites:
- parse_eggnog_results.py must be completed to generate genome_cog_matrix.csv
- The file contains: genome IDs, COG family presence/absence (0/1), target variable s_aa_freq

Input: data/processed/genome_cog_matrix.csv
Output: Model files, performance evaluation results, SHAP analysis results

前置要求:
- 已完成 parse_eggnog_results.py，生成 genome_cog_matrix.csv
- 该文件包含: 基因组ID、各COG家族的存在/缺失值(0/1)、目标变量 s_aa_freq

输入: data/processed/genome_cog_matrix.csv
输出: 模型文件、性能评估结果、SHAP分析结果
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import time
import shap
import joblib
import warnings
import os
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LassoCV, RidgeCV
from sklearn.ensemble import RandomForestRegressor, ExtraTreesRegressor
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
from sklearn.feature_selection import VarianceThreshold
from sklearn.inspection import permutation_importance
from xgboost import XGBRegressor
from tqdm import tqdm

warnings.filterwarnings("ignore", category=UserWarning)

# Set font embedding for EPS/PDF output
plt.rcParams['ps.fonttype'] = 42
plt.rcParams['pdf.fonttype'] = 42

# Create results directory
os.makedirs('results', exist_ok=True)

# ==========================================
# 1. Load data (from parse_eggnog_results.py output)
# ==========================================
print("=" * 70)
print("Step 1: Loading COG binary matrix")
print("=" * 70)
print("Data source: genome_cog_matrix.csv generated by parse_eggnog_results.py")
print("Description: 1,967 representative genomes × 8,676 COG families (0/1 binary matrix)")
print("-" * 70)

INPUT_MATRIX = "data/processed/genome_cog_matrix.csv"

df = pd.read_csv(INPUT_MATRIX, index_col=0, low_memory=False)
print(f"Genomes loaded: {len(df)}")
print(f"Raw COG families: {len([c for c in df.columns if c.startswith('COG')])}")

# Extract COG feature matrix (columns starting with 'COG')
X_counts = df.filter(regex='^COG')
print(f"COG feature columns extracted: {X_counts.shape[1]}")

# Ensure data is binary matrix (presence/absence)
X_binary = (X_counts > 0).astype(np.int8)
print("Converted to binary matrix (0=absent, 1=present)")

# Target variable
target = 's_aa_freq'
if target not in df.columns:
    raise ValueError(f"Target variable '{target}' not found in input file")
y = df[target]
print(f"Target variable: {target}")
print(f"Target range: [{y.min():.4f}, {y.max():.4f}]")

# ==========================================
# 2. Low variance feature filtering
# ==========================================
print("\n" + "=" * 70)
print("Step 2: Low variance feature filtering")
print("=" * 70)

# Filter out features that are consistent in >99.8% of genomes (weak features)
selector = VarianceThreshold(threshold=0.998 * (1 - 0.998))
X_filtered = selector.fit_transform(X_binary)
kept_columns = X_binary.columns[selector.get_support()].tolist()
print(f"Features before low variance filtering: {X_binary.shape[1]}")
print(f"Features after low variance filtering: {len(kept_columns)}")
print(f"Features removed: {X_binary.shape[1] - len(kept_columns)}")

X = pd.DataFrame(X_filtered, columns=kept_columns)

# ==========================================
# 3. Split training and test sets
# ==========================================
print("\n" + "=" * 70)
print("Step 3: Splitting training and test sets (80% / 20%)")
print("=" * 70)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=123
)
print(f"Training set size: {len(X_train)}")
print(f"Test set size: {len(X_test)}")

# Standardization
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
print("Features standardized (mean=0, std=1)")

# ==========================================
# 4. Feature selection: Permutation importance with Random Forest
# ==========================================
print("\n" + "=" * 70)
print("Step 4: Feature selection (Permutation Importance, keep 95% cumulative importance)")
print("=" * 70)

print("Training temporary Random Forest model...")
rf_temp = RandomForestRegressor(
    n_estimators=100, 
    max_depth=10, 
    n_jobs=4, 
    random_state=123
)
rf_temp.fit(X_train_scaled, y_train)

print("Computing permutation importance...")
perm_result = permutation_importance(
    rf_temp, X_test_scaled, y_test, 
    n_repeats=5, random_state=123, n_jobs=4
)

perm_df = pd.DataFrame({
    'feature': X_train.columns,
    'importance_mean': perm_result.importances_mean
}).sort_values('importance_mean', ascending=False)

# Keep features with cumulative importance <= 95%
cumsum = perm_df['importance_mean'].cumsum() / perm_df['importance_mean'].sum()
n_select = (cumsum <= 0.95).sum()
selected_features = perm_df['feature'].head(n_select).tolist()

print(f"Features before selection: {X_train.shape[1]}")
print(f"Features after selection: {len(selected_features)}")
print(f"Retained cumulative importance: {cumsum.iloc[n_select-1]:.2%}")

# Save selected feature list
pd.DataFrame({'COG': selected_features}).to_csv('results/selected_features.tsv', 
                                                sep='\t', index=False)
print("Selected feature list saved to: results/selected_features.tsv")

# Use selected features
X_train_sel = X_train[selected_features]
X_test_sel = X_test[selected_features]
X_train_sel_scaled = scaler.fit_transform(X_train_sel)
X_test_sel_scaled = scaler.transform(X_test_sel)

# ==========================================
# 5. Define 5 regression models
# ==========================================
print("\n" + "=" * 70)
print("Step 5: Defining 5 regression models")
print("=" * 70)

models = {
    "LassoCV": LassoCV(
        cv=5, max_iter=5000, n_jobs=4, 
        random_state=123, tol=1e-3
    ),
    "RidgeCV": RidgeCV(
        cv=5, alphas=np.logspace(-6, 6, 13)
    ),
    "RandomForest": RandomForestRegressor(
        n_estimators=600, min_samples_split=4, min_samples_leaf=2,
        max_features=0.2, max_depth=None, bootstrap=False,
        random_state=123, n_jobs=4
    ),
    "ExtraTrees": ExtraTreesRegressor(
        n_estimators=400, max_features=0.3, max_depth=None,
        random_state=123, n_jobs=4
    ),
    "XGBoost": XGBRegressor(
        n_estimators=600, max_depth=6, learning_rate=0.05,
        subsample=0.8, colsample_bytree=0.6, reg_lambda=1.0,
        random_state=123, n_jobs=4, tree_method='hist'
    )
}

print("Models defined:")
for name in models.keys():
    print(f"  - {name}")

# ==========================================
# 6. Train models and evaluate baseline performance
# ==========================================
print("\n" + "=" * 70)
print("Step 6: Training models and evaluating baseline performance")
print("=" * 70)

model_performance = []

for name, model in models.items():
    print(f"\nTraining {name}...")
    try:
        start_time = time.time()
        model.fit(X_train_sel_scaled, y_train)
        train_time = time.time() - start_time
        
        # Training set predictions
        y_train_pred = model.predict(X_train_sel_scaled)
        train_r2 = r2_score(y_train, y_train_pred)
        
        # Test set predictions
        y_test_pred = model.predict(X_test_sel_scaled)
        test_r2 = r2_score(y_test, y_test_pred)
        test_mse = mean_squared_error(y_test, y_test_pred)
        test_mae = mean_absolute_error(y_test, y_test_pred)
        
        model_performance.append({
            'Model': name,
            'Train R²': train_r2,
            'Test R²': test_r2,
            'Test MSE': test_mse,
            'Test MAE': test_mae,
            'Train Time (s)': train_time
        })
        
        print(f"  Training time: {train_time:.2f} sec")
        print(f"  Training R²: {train_r2:.4f}")
        print(f"  Test R²: {test_r2:.4f}")
        print(f"  Test MSE: {test_mse:.6f}")
        print(f"  Test MAE: {test_mae:.6f}")
        
    except Exception as e:
        print(f"  !!! {name} training failed: {str(e)}")
        continue

# Save model performance comparison
perf_df = pd.DataFrame(model_performance).sort_values('Test R²', ascending=False)
perf_df.to_csv('results/model_performance_comparison.tsv', sep='\t', index=False)
print("\n" + "-" * 70)
print("Model performance comparison:")
print(perf_df.to_string(index=False))

# ==========================================
# 7. Robustness evaluation (randomly remove 10%-50% of COG features)
# ==========================================
print("\n" + "=" * 70)
print("Step 7: Robustness evaluation (randomly remove 10%-50% of COG features)")
print("=" * 70)

removal_rates = [0.0, 0.1, 0.2, 0.3, 0.4, 0.5]
robustness_results = []

for name, model in models.items():
    print(f"\nEvaluating {name} robustness...")
    
    # Ensure model is trained
    try:
        model.predict(X_test_sel_scaled[:1])
    except:
        model.fit(X_train_sel_scaled, y_train)
    
    base_pred = model.predict(X_test_sel_scaled)
    base_r2 = r2_score(y_test, base_pred)
    
    model_robust = [{'rate': 0.0, 'test_r2': base_r2}]
    
    for rate in tqdm(removal_rates[1:], desc=f"{name} perturbation", leave=False):
        try:
            # Randomly set rate proportion of 1's to 0 (simulating feature loss)
            X_test_pert = X_test_sel.copy()
            mask = np.random.rand(*X_test_pert.shape) < rate
            X_test_pert = X_test_pert.mask(mask & (X_test_pert == 1), 0)
            X_test_pert_scaled = scaler.transform(X_test_pert)
            
            pred_pert = model.predict(X_test_pert_scaled)
            r2_pert = r2_score(y_test, pred_pert)
            model_robust.append({'rate': rate, 'test_r2': r2_pert})
        except Exception as e:
            print(f"  !!! {name} @ {rate*100}% perturbation failed: {str(e)}")
            model_robust.append({'rate': rate, 'test_r2': np.nan})
    
    for r in model_robust:
        r['model'] = name
    robustness_results.extend(model_robust)

robust_df = pd.DataFrame(robustness_results)
robust_summary = robust_df.pivot(index='model', columns='rate', values='test_r2').reset_index()
robust_summary.columns = ['Model'] + [f'R²@{int(r*100)}%' for r in removal_rates[1:]]
robust_summary['Base_R²'] = robust_summary['R²@10%'].fillna(0)
for name in models.keys():
    base_r2 = robust_df[(robust_df['model']==name) & (robust_df['rate']==0.0)]['test_r2'].values
    if len(base_r2) > 0:
        robust_summary.loc[robust_summary['Model']==name, 'Base_R²'] = base_r2[0]

robust_summary = robust_summary.sort_values('Base_R²', ascending=False)
robust_summary.to_csv('results/model_robustness_comparison.tsv', sep='\t', index=False)

print("\nRobustness evaluation results:")
print(robust_summary.to_string(index=False))

# ==========================================
# 8. Select best model (based on test R²)
# ==========================================
print("\n" + "=" * 70)
print("Step 8: Selecting best model")
print("=" * 70)

# Select best model based on test R²
best_model_name = perf_df.iloc[0]['Model']
best_test_r2 = perf_df.iloc[0]['Test R²']

print(f"Best model selected by test R²:")
print(f"  Best model: {best_model_name}")
print(f"  Test R²: {best_test_r2:.4f}")

# Retrain best model
best_model = models[best_model_name]
best_model.fit(X_train_sel_scaled, y_train)

# ==========================================
# 9. Save best model and all necessary files (for prediction script)
# ==========================================
print("\n" + "=" * 70)
print("Step 9: Saving best model and necessary files")
print("=" * 70)

# Save model with unified name for prediction script
joblib.dump(best_model, 'results/best_model.pkl')
print("Best model saved to: results/best_model.pkl")

# Save copy with model name for traceability
joblib.dump(best_model, f'results/best_model_{best_model_name}.pkl')
print(f"Best model copy saved to: results/best_model_{best_model_name}.pkl")

# Save scaler
joblib.dump(scaler, 'results/scaler.pkl')
print("Scaler saved to: results/scaler.pkl")

# Save selected features list
joblib.dump(selected_features, 'results/selected_features.pkl')
print("Selected features list saved to: results/selected_features.pkl")

# Save model summary
model_summary = {
    'best_model': best_model_name,
    'test_r2': float(best_test_r2),
    'n_features': len(selected_features),
    'n_training_samples': len(X_train),
    'n_test_samples': len(X_test)
}
pd.DataFrame([model_summary]).to_csv('results/model_summary.tsv', sep='\t', index=False)
print("Model summary saved to: results/model_summary.tsv")

# ==========================================
# 10. Generate predicted vs actual scatter plot
# ==========================================
print("\n" + "=" * 70)
print("Step 10: Generating predicted vs actual scatter plot")
print("=" * 70)

y_pred = best_model.predict(X_test_sel_scaled)
plt.figure(figsize=(8, 8))
sns.scatterplot(x=y_pred, y=y_test, alpha=0.7, s=50, edgecolor='none', color='steelblue')
min_val = min(min(y_pred), min(y_test))
max_val = max(max(y_pred), max(y_test))
plt.plot([min_val, max_val], [min_val, max_val], 'r--', lw=2.5, label='y = x')
sns.regplot(x=y_pred, y=y_test, scatter=False, color='orange', line_kws={'lw': 2.8}, ci=95, label='Regression line (95% CI)')
plt.xlabel(f"Predicted value ({best_model_name})", fontsize=14)
plt.ylabel("Actual value (SAA frequency)", fontsize=14)
plt.title(f"Predicted vs Actual\n{best_model_name} R² = {best_test_r2:.4f}", fontsize=15)
plt.legend(fontsize=12, loc='upper left')
plt.grid(True, linestyle='--', alpha=0.4)
plt.axis('equal')
plt.tight_layout()
plt.savefig('results/pred_vs_true.eps', format='eps', dpi=300, bbox_inches='tight')
plt.savefig('results/pred_vs_true.pdf', format='pdf', dpi=400, bbox_inches='tight')
plt.close()
print("Predicted vs actual scatter plot saved to: results/pred_vs_true.eps/.pdf")

# ==========================================
# 11. SHAP analysis (interpret model predictions)
# ==========================================
print("\n" + "=" * 70)
print("Step 11: SHAP analysis - quantifying feature contributions")
print("=" * 70)

print(f"Performing SHAP analysis on best model {best_model_name}...")

if best_model_name in ["LassoCV", "RidgeCV"]:
    explainer = shap.LinearExplainer(best_model, X_train_sel_scaled)
else:
    explainer = shap.TreeExplainer(best_model)

shap_values = explainer.shap_values(X_test_sel_scaled)

# Calculate mean absolute SHAP values (feature importance)
shap_importance = np.abs(shap_values).mean(axis=0)
shap_importance_df = pd.DataFrame({
    'feature': selected_features,
    'mean_abs_shap': shap_importance
}).sort_values('mean_abs_shap', ascending=False).reset_index(drop=True)

# Save full SHAP importance
shap_importance_df.to_csv('results/shap_feature_importance_all.tsv', sep='\t', index=False)

# Top 10 important features
top10_shap = shap_importance_df.head(10).round(6)
print("\nSHAP importance - Top 10 COG features:")
print(top10_shap.to_string(index=False))
top10_shap.to_csv('results/shap_top10_importance.tsv', sep='\t', index=False)

# Extract detailed information for top 10 features
top10_features = top10_shap['feature'].tolist()
top10_indices = [selected_features.index(f) for f in top10_features]

# Save complete scatter data
shap_scatter_top10 = pd.DataFrame(
    shap_values[:, top10_indices],
    columns=[f"SHAP_{f}" for f in top10_features]
)
for f in top10_features:
    shap_scatter_top10[f] = X_test_sel[f].values
shap_scatter_top10['true_y'] = y_test.values
shap_scatter_top10['pred_y'] = best_model.predict(X_test_sel_scaled)
shap_scatter_top10['sample_idx'] = X_test.index

cols_order = ['sample_idx'] + top10_features + [f"SHAP_{f}" for f in top10_features] + ['true_y', 'pred_y']
shap_scatter_top10 = shap_scatter_top10[cols_order]
shap_scatter_top10.to_csv('results/shap_scatter_top10_data.tsv', sep='\t', index=False, float_format='%.6f')

# Generate SHAP summary plot
plt.figure(figsize=(12, 8))
shap.summary_plot(
    shap_values[:, top10_indices],
    X_test_sel[top10_features],
    max_display=10,
    show=False,
    plot_type="dot"
)
plt.title(f"SHAP Summary - Top 10 Features ({best_model_name})\nTarget: SAA Frequency", fontsize=14, pad=20)
plt.xlabel("SHAP value (contribution to prediction)", fontsize=12)
plt.tight_layout()
plt.savefig('results/shap_summary_top10.eps', format='eps', dpi=300, bbox_inches='tight')
plt.savefig('results/shap_summary_top10.pdf', format='pdf', dpi=400, bbox_inches='tight')
plt.close()
print("SHAP summary plot saved to: results/shap_summary_top10.eps/.pdf")

# Generate SHAP bar plot (feature importance)
plt.figure(figsize=(10, 8))
shap.summary_plot(
    shap_values[:, top10_indices],
    X_test_sel[top10_features],
    max_display=10,
    show=False,
    plot_type="bar"
)
plt.title(f"SHAP Feature Importance - Top 10 ({best_model_name})", fontsize=14)
plt.tight_layout()
plt.savefig('results/shap_bar_top10.eps', format='eps', dpi=300, bbox_inches='tight')
plt.savefig('results/shap_bar_top10.pdf', format='pdf', dpi=400, bbox_inches='tight')
plt.close()
print("SHAP bar plot saved to: results/shap_bar_top10.eps/.pdf")

# ==========================================
# 12. Final summary
# ==========================================
print("\n" + "=" * 70)
print("Analysis completed - Summary")
print("=" * 70)
print(f"""
Input files:
  - genome_cog_matrix.csv: {len(df)} genomes × {X_counts.shape[1]} COG families

Feature filtering:
  - After low variance filtering: {len(kept_columns)} COGs
  - Permutation importance (95%): {len(selected_features)} key COGs

Model performance:
  - Best model: {best_model_name}
  - Test R²: {best_test_r2:.4f}

Output files (results/ directory):
  - selected_features.tsv           : {len(selected_features)} selected key COG features
  - model_performance_comparison.tsv: 5-model performance comparison
  - model_robustness_comparison.tsv : Robustness evaluation results
  - model_summary.tsv               : Model summary information
  - best_model.pkl                  : Best model file (for prediction script)
  - best_model_{best_model_name}.pkl: Best model copy
  - scaler.pkl                      : Standardizer
  - pred_vs_true.eps/.pdf           : Predicted vs actual scatter plot
  - shap_feature_importance_all.tsv : Full SHAP feature importance
  - shap_top10_importance.tsv       : Top 10 SHAP feature importance
  - shap_summary_top10.eps/.pdf     : SHAP summary plot
  - shap_bar_top10.eps/.pdf         : SHAP bar plot
""")

print("\nAll steps completed!")
print("\nNote: Prediction script should use the following files:")
print("  - results/best_model.pkl")
print("  - results/scaler.pkl")
print("  - results/selected_features.pkl")